#!/usr/bin/env python3
"""Merge data/qdqc.db (primary) + data/qdqc-new.db extras into remote Postgres."""
from __future__ import annotations

import os
import sqlite3
import sys
from pathlib import Path

import psycopg

ROOT = Path(__file__).resolve().parents[1]
PRIMARY = ROOT / "data" / "qdqc.db"
SECONDARY = ROOT / "data" / "qdqc-new.db"
PG_URL = os.environ.get("QDQC_DATABASE_URL", "").strip()
if not PG_URL:
    env_path = ROOT / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line.startswith("QDQC_DATABASE_URL="):
                PG_URL = line.split("=", 1)[1].strip().strip('"').strip("'")
                break
if not PG_URL:
    print("Set QDQC_DATABASE_URL or create .env", file=sys.stderr)
    raise SystemExit(2)
# psycopg accepts postgres:// and postgresql://
if PG_URL.startswith("postgres://"):
    PG_URL = "postgresql://" + PG_URL[len("postgres://") :]


# Load primary wholesale; then add secondary rows missing by natural key.
NATURAL_KEY = {
    "columns": "slug",
    "tags": "slug",
    "posts": "slug",
    "news": "url",
    "topics": "title",
    "comments": ("post_slug", "author", "body", "created_at"),
    "web_users": "username",
    "web_permissions": "code",
    "web_roles": "name",
    "_marqdo_migrations": "version",
}

TABLE_ORDER = [
    "columns",
    "tags",
    "posts",
    "news",
    "post_tags",
    "topics",
    "replies",
    "comments",
    "web_permissions",
    "web_roles",
    "web_role_permissions",
    "web_users",
    "web_user_roles",
    "_marqdo_migrations",
]


def exists(con: sqlite3.Connection, table: str) -> bool:
    return (
        con.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
        ).fetchone()
        is not None
    )


def fetch(con: sqlite3.Connection, table: str):
    cols = [r[1] for r in con.execute(f'PRAGMA table_info("{table}")')]
    rows = con.execute(f'SELECT * FROM "{table}"').fetchall()
    return cols, rows


def row_key(cols, row, key):
    if isinstance(key, tuple):
        idx = [cols.index(k) for k in key]
        return tuple(row[i] for i in idx)
    return row[cols.index(key)]


def align(cols_dst, cols_src, rows_src):
    si = {c: i for i, c in enumerate(cols_src)}
    out = []
    for r in rows_src:
        out.append(tuple(r[si[c]] if c in si else None for c in cols_dst))
    return out


def pg_create(cur) -> None:
    stmts = [
        '''CREATE TABLE IF NOT EXISTS columns (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, summary TEXT,
          sort_order INTEGER, status TEXT, created_at TEXT)''',
        '''CREATE TABLE IF NOT EXISTS tags (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE)''',
        '''CREATE TABLE IF NOT EXISTS posts (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, summary TEXT, content TEXT,
          tag TEXT, created_at TEXT, updated_at TEXT, column_slug TEXT, pinned INTEGER DEFAULT 0)''',
        '''CREATE TABLE IF NOT EXISTS news (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT NOT NULL, url TEXT NOT NULL, source TEXT, summary TEXT,
          published_at TEXT, created_at TEXT)''',
        '''CREATE TABLE IF NOT EXISTS post_tags (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          post_id INTEGER, tag_id INTEGER)''',
        '''CREATE TABLE IF NOT EXISTS topics (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT NOT NULL, summary TEXT, content TEXT, author TEXT,
          created_at TEXT, updated_at TEXT)''',
        '''CREATE TABLE IF NOT EXISTS replies (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          topic_id INTEGER, author TEXT, content TEXT, created_at TEXT)''',
        '''CREATE TABLE IF NOT EXISTS comments (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          post_slug TEXT NOT NULL, author TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT)''',
        '''CREATE TABLE IF NOT EXISTS web_permissions (
          code TEXT PRIMARY KEY, resource TEXT NOT NULL, action TEXT NOT NULL, description TEXT)''',
        '''CREATE TABLE IF NOT EXISTS web_roles (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL UNIQUE, is_system INTEGER NOT NULL DEFAULT 0, tenant_id TEXT)''',
        '''CREATE TABLE IF NOT EXISTS web_role_permissions (
          role_id INTEGER NOT NULL, permission_code TEXT NOT NULL,
          PRIMARY KEY (role_id, permission_code))''',
        '''CREATE TABLE IF NOT EXISTS web_users (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at TEXT)''',
        '''CREATE TABLE IF NOT EXISTS web_user_roles (
          user_id INTEGER NOT NULL, role_id INTEGER NOT NULL, tenant_id TEXT NOT NULL DEFAULT '',
          PRIMARY KEY (user_id, role_id, tenant_id))''',
        '''CREATE TABLE IF NOT EXISTS _marqdo_migrations (
          version INTEGER PRIMARY KEY, applied_at TEXT)''',
        '''CREATE TABLE IF NOT EXISTS _marqdo_sessions (
          id TEXT PRIMARY KEY, expires_at BIGINT NOT NULL, data TEXT NOT NULL)''',
    ]
    for s in stmts:
        cur.execute(s)


def insert_rows(cur, table, cols, rows, keep_id=True):
    if not rows:
        return 0
    use_cols = list(cols)
    use_rows = list(rows)
    if not keep_id and "id" in use_cols:
        ii = use_cols.index("id")
        use_cols = [c for c in use_cols if c != "id"]
        use_rows = [tuple(v for i, v in enumerate(r) if i != ii) for r in use_rows]
    ph = ",".join(["%s"] * len(use_cols))
    col_list = ",".join(f'"{c}"' for c in use_cols)
    cur.executemany(f'INSERT INTO "{table}" ({col_list}) VALUES ({ph})', use_rows)
    return len(use_rows)


def reset_id(cur, table):
    cur.execute(
        """SELECT setval(pg_get_serial_sequence(%s, 'id'),
           COALESCE((SELECT MAX(id) FROM """ + f'"{table}"' + """), 1), true)""",
        (table,),
    )


def main() -> int:
    if not PRIMARY.exists():
        print("missing", PRIMARY, file=sys.stderr)
        return 1
    primary = sqlite3.connect(PRIMARY)
    secondary = sqlite3.connect(SECONDARY) if SECONDARY.exists() else None

    with psycopg.connect(PG_URL) as pg:
        with pg.cursor() as cur:
            pg_create(cur)
            for t in reversed(TABLE_ORDER):
                cur.execute(f'DELETE FROM "{t}"')
            pg.commit()

            # post_id / tag_id remaps when adding secondary posts/tags
            post_id_map: dict[int, int] = {}
            tag_id_map: dict[int, int] = {}
            topic_id_map: dict[int, int] = {}

            for table in TABLE_ORDER:
                if not exists(primary, table):
                    print(f"skip {table}")
                    continue
                cols, prow = fetch(primary, table)
                n = insert_rows(cur, table, cols, prow, keep_id=True)
                print(f"{table}: primary {n}")
                if "id" in cols:
                    # identity map primary id -> same id
                    ii = cols.index("id")
                    if table == "posts":
                        post_id_map = {r[ii]: r[ii] for r in prow}
                    elif table == "tags":
                        tag_id_map = {r[ii]: r[ii] for r in prow}
                    elif table == "topics":
                        topic_id_map = {r[ii]: r[ii] for r in prow}
                    reset_id(cur, table)

                # secondary extras
                if not secondary or not exists(secondary, table):
                    continue
                scols, srows = fetch(secondary, table)
                srows = align(cols, scols, srows)
                key = NATURAL_KEY.get(table)
                if key is None:
                    # post_tags / replies / web_role_* — only add if parent keys exist after remap
                    if table == "post_tags":
                        pi, ti = cols.index("post_id"), cols.index("tag_id")
                        # build slug maps from already-loaded primary+new posts/tags via DB
                        cur.execute('SELECT id, slug FROM posts')
                        slug_to_pid = {r[1]: r[0] for r in cur.fetchall()}
                        cur.execute('SELECT id, slug FROM tags')
                        slug_to_tid = {r[1]: r[0] for r in cur.fetchall()}
                        # secondary post/tag id -> slug
                        if exists(secondary, "posts") and exists(secondary, "tags"):
                            sp = {r[0]: r[2] for r in secondary.execute("SELECT id, title, slug FROM posts")}
                            st = {r[0]: r[2] for r in secondary.execute("SELECT id, name, slug FROM tags")}
                            # also need from earlier secondary fetch of posts - use secondary conn
                            sp = {
                                r[0]: r[1]
                                for r in secondary.execute('SELECT id, slug FROM posts')
                            }
                            st = {
                                r[0]: r[1]
                                for r in secondary.execute('SELECT id, slug FROM tags')
                            }
                            cur.execute("SELECT post_id, tag_id FROM post_tags")
                            have = set(cur.fetchall())
                            extra = []
                            for r in srows:
                                pslug = sp.get(r[pi])
                                tslug = st.get(r[ti])
                                if not pslug or not tslug:
                                    continue
                                np, nt = slug_to_pid.get(pslug), slug_to_tid.get(tslug)
                                if np is None or nt is None:
                                    continue
                                if (np, nt) in have:
                                    continue
                                extra.append((np, nt))
                                have.add((np, nt))
                            if extra:
                                cur.executemany(
                                    'INSERT INTO post_tags (post_id, tag_id) VALUES (%s,%s)',
                                    extra,
                                )
                                print(f"  +{len(extra)} post_tags from qdqc-new")
                    elif table == "replies":
                        # skip orphan replies; primary already has more replies
                        pass
                    elif table in ("web_role_permissions", "web_user_roles"):
                        pass
                    continue

                have = {row_key(cols, r, key) for r in prow}
                extras = []
                for r in srows:
                    k = row_key(cols, r, key)
                    if k in have:
                        continue
                    have.add(k)
                    extras.append(r)
                if not extras:
                    continue
                # insert without old ids so identity assigns fresh ids
                added = insert_rows(cur, table, cols, extras, keep_id=False)
                print(f"  +{added} from qdqc-new")
                if "id" in cols:
                    reset_id(cur, table)

            pg.commit()
            print("--- postgres counts ---")
            for table in TABLE_ORDER + ["_marqdo_sessions"]:
                cur.execute(
                    "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema='public' AND table_name=%s)",
                    (table,),
                )
                if not cur.fetchone()[0]:
                    continue
                cur.execute(f'SELECT count(*) FROM "{table}"')
                print(f"  {table}: {cur.fetchone()[0]}")

            # show post slugs
            cur.execute("SELECT slug FROM posts ORDER BY id")
            print("posts:", [r[0] for r in cur.fetchall()])

    primary.close()
    if secondary:
        secondary.close()
    print("OK →", PG_URL.split("@")[-1])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
